#!/bin/sh
cd ~
if ! [ -d ./payroll-smb ]; then
    echo "The ./payroll-smb folder does not exist. Let's create it."
    mkdir payroll-smb
fi
cd payroll-smb
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/docker-compose.yml >docker-compose.yml
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/.env.docker >.env.docker
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/start >start
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/stop >stop
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/update >update
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/logs >logs
curl https://raw.githubusercontent.com/serhii-untilov/Payroll-SMB/master/stats >stats
chmod +x ./start
chmod +x ./stop
chmod +x ./update
chmod +x ./logs
chmod +x ./stats
./stop
docker compose pull
./start
