#!/bin/bash
npm --workspace=@repo/api run build
npm run db
rm -rf ./packages/openapi
npm --workspace=@repo/api run swagger
npx openapi-generator-cli generate -i ./apps/api/swagger.json -o ./packages/openapi -g typescript-axios --skip-validate-spec
