#!/bin/bash
npm --workspace=@repo/api run build
npm run db
rm -rf ./packages/openapi/src
npm --workspace=@repo/api run swagger

npx openapi-generator-cli generate -i ./apps/api/swagger.json -o ./packages/openapi/src \
    -g typescript-axios #--skip-validate-spec
