on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: payroll-smb

jobs:
    build:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
