on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: payroll-smb

jobs:
    build:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache Local Images
              id: local-images
              uses: actions/cache@v3
              with:
                  path: /var/lib/docker/
                  key: local-docker-directory
            - name: Build Images
              working-directory: .
              run: docker compose build
